# Generated by Django 4.0.2 on 2022-04-09 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loanapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createuser',
            name='loan_terms',
        ),
        migrations.RemoveField(
            model_name='createuser',
            name='loan_type',
        ),
    ]
